version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'batel'
    ports:
      - "3306:3306"

  attendance:
    image: attendance_image
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"